- connstr: "redis://:Eiwj2zcT2q@10.2.4.35:30237/2" #redis://:passwd@host:port/<db>
  monitor:
    soa_payment_queue_delayed1: #监控指标，由组名_服务名_为前缀
      command: [llen, cc] #redis命令以数组格式配置
      desc: "延迟1队列长度"